/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdio.h>

int main(void)
{
	uint32_t *pClkCtrlReg     = (uint32_t *)0x40023830;
	uint32_t *pPortAModeReg   = (uint32_t *)0x40020000;
	uint32_t *pPortAInDatReg  = (uint32_t *)0x40020010;

	// Enable clock RCC AHB1_ENR FOR GPIOA
	*pClkCtrlReg |=  (1);

	// Set GPIOA mode to input
	*pPortAModeReg &= ~(3);

	// Logic that reads input data from PA0
    while(1)
    {
    	if((*pPortAInDatReg & 1)== 0)
    		printf("Obstacle Is Detected");
    	else
    		printf("No Obstacle Detected");
    }
}
